import type { AnimationDef, CompiledAnimation, KeyframesDef } from "../compile/types";
import { type ComponentExportOptions, PROPS_TYPE, renderRoot, VISUALLY_HIDDEN } from "./component";
import { templateLiteral, toJsLiteral } from "./jsx";
import { buildCss, classedRoot, groupRules, uniqueGroups } from "./shared";

type MotionValue = number | string;

export type MotionTrack = {
  selector: string;
  keyframes: Record<string, MotionValue[]>;
  options: {
    duration: number;
    delay: number;
    ease: string | number[];
    times: number[];
    repeat: number;
    repeatType: "loop" | "reverse";
  };
  /** Not the last animation of its element: `loop` must not repeat it, or the next step never starts. */
  step?: true;
};

const EASES: Record<string, string | number[]> = {
  linear: "linear",
  ease: [0.25, 0.1, 0.25, 1],
  "ease-in": "easeIn",
  "ease-out": "easeOut",
  "ease-in-out": "easeInOut",
};

function toMotionEntries(property: string, value: string): [string, MotionValue][] {
  const scale = /^scale\(\s*(-?[\d.]+)\s*\)$/.exec(value);
  if (property === "transform" && scale) return [["scale", Number(scale[1])]];
  const key = property.replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase());
  return [[key, /^-?\d*\.?\d+$/.test(value) ? Number(value) : value]];
}

/** CSS keyframes (offset → props) → Motion value arrays + `times`, carrying missing values. */
export function toMotionKeyframes(definition: KeyframesDef): {
  keyframes: Record<string, MotionValue[]>;
  times: number[];
} {
  const stops = [...definition.stops].sort((a, b) => a.offset - b.offset);
  const perStop = stops.map((stop) =>
    Object.fromEntries(
      Object.entries(stop.props).flatMap(([property, value]) => toMotionEntries(property, value)),
    ),
  );
  const keys = [...new Set(perStop.flatMap((values) => Object.keys(values)))];
  const keyframes: Record<string, MotionValue[]> = {};
  for (const key of keys) {
    let last: MotionValue | undefined = perStop.find((values) => key in values)?.[key];
    keyframes[key] = perStop.map((values) => {
      if (key in values) last = values[key];
      return last as MotionValue;
    });
  }
  return { keyframes, times: stops.map((stop) => stop.offset) };
}

export function toMotionTrack(
  selector: string,
  animation: AnimationDef,
  definition: KeyframesDef,
): MotionTrack {
  let { keyframes, times } = toMotionKeyframes(definition);
  const reversed = animation.direction === "reverse" || animation.direction === "alternate-reverse";
  if (reversed) {
    keyframes = Object.fromEntries(
      Object.entries(keyframes).map(([key, values]) => [key, [...values].reverse()]),
    );
    times = times.map((time) => Math.round((1 - time) * 10_000) / 10_000).reverse();
  }
  const ease =
    typeof animation.easing === "string"
      ? (EASES[animation.easing] ?? "linear")
      : [...animation.easing.cubicBezier];
  return {
    selector,
    keyframes,
    options: {
      duration: animation.duration / 1000,
      delay: animation.delay / 1000,
      ease,
      times,
      repeat:
        animation.iterations === "infinite"
          ? Number.POSITIVE_INFINITY
          : Math.max(0, animation.iterations - 1),
      repeatType: animation.direction.startsWith("alternate") ? "reverse" : "loop",
    },
  };
}

/**
 * Same props contract as the React export, animated with `motion/react`. The CSS keeps static
 * props, the first keyframe (so nothing flashes before hydration) and the reduced-motion block;
 * `useAnimate` plays the keyframes. `speed` and `paused` use the playback controls directly.
 */
export function exportMotion(
  compiled: CompiledAnimation,
  options: ComponentExportOptions = {},
): string {
  const name = options.componentName ?? "AnimatedLogo";
  const groups = groupRules(compiled.id, compiled.rules);
  const unique = uniqueGroups(groups);
  const root = classedRoot(compiled, groups);
  const css = buildCss(compiled, unique, "none");
  const status = compiled.a11y.mode === "status";
  const definitions = new Map(
    compiled.keyframes.map((definition) => [definition.name, definition]),
  );
  const tracks = unique.flatMap(({ className, rule }) =>
    rule.animations.flatMap((animation, index, all) => {
      const definition = definitions.get(animation.keyframes);
      if (!definition) return [];
      const track = toMotionTrack(`.${className}`, animation, definition);
      return [index < all.length - 1 ? { ...track, step: true as const } : track];
    }),
  );
  const sequenced = tracks.some((track) => track.step);

  return `"use client";

import {
  type AnimationOptions,
  type AnimationPlaybackControls,
  type DOMKeyframesDefinition,
  useAnimate,
  useReducedMotion,
} from "motion/react";
import { ${status ? "type CSSProperties, " : ""}useEffect, useRef } from "react";

// Generated by strokit. Colors follow --sk-stroke; prefers-reduced-motion shows the final frame.
const css = ${templateLiteral(`\n${css}\n`)};

type Track = { selector: string; keyframes: DOMKeyframesDefinition; options: AnimationOptions${sequenced ? "; step?: true" : ""} };

const tracks: Track[] = ${toJsLiteral(tracks)};
${status ? `\n${VISUALLY_HIDDEN}\n` : ""}
${PROPS_TYPE(name, compiled.a11y.label)}

export function ${name}({
  size,
  speed = 1,
  loop,
  paused = false,
  className,
  label = ${JSON.stringify(compiled.a11y.label)},
}: ${name}Props) {
  const [scope, animate] = useAnimate<SVGSVGElement>();
  const reducedMotion = useReducedMotion();
  const controls = useRef<AnimationPlaybackControls[]>([]);

  useEffect(() => {
    if (reducedMotion) return;
    controls.current = tracks.map((track) =>
      animate(track.selector, track.keyframes, {
        ...track.options,
        ...(loop === undefined${sequenced ? " || track.step" : ""} ? {} : { repeat: loop ? Number.POSITIVE_INFINITY : 0 }),
      }),
    );
    return () => {
      for (const control of controls.current) control.stop();
      controls.current = [];
    };
  }, [animate, loop, reducedMotion]);

  useEffect(() => {
    for (const control of controls.current) {
      control.speed = speed;
      if (paused) control.pause();
      else control.play();
    }
  }, [speed, paused, loop, reducedMotion]);

  return (
${renderRoot(compiled, root, ["ref={scope}"])}
  );
}
`;
}
