import type { CompiledAnimation } from "../compile/types";
import { type ComponentExportOptions, PROPS_TYPE, renderRoot, VISUALLY_HIDDEN } from "./component";
import { templateLiteral } from "./jsx";
import { buildCss, classedRoot, groupRules, uniqueGroups } from "./shared";

/**
 * Typed React component with no dependency besides React. The CSS is the same as the CSS
 * export, except that timing reads `--sk-speed`, `--sk-iterations` and `--sk-play-state`,
 * so `speed`, `loop` and `paused` change playback without re-rendering the SVG.
 */
export function exportReact(
  compiled: CompiledAnimation,
  options: ComponentExportOptions = {},
): string {
  const name = options.componentName ?? "AnimatedLogo";
  const groups = groupRules(compiled.id, compiled.rules);
  const root = classedRoot(compiled, groups);
  const css = buildCss(compiled, uniqueGroups(groups), "variables");
  const status = compiled.a11y.mode === "status";

  return `import type { CSSProperties } from "react";

// Generated by strokekit. Colors follow --sk-stroke; prefers-reduced-motion shows the final frame.
const css = ${templateLiteral(`\n${css}\n`)};
${status ? `\n${VISUALLY_HIDDEN}\n` : ""}
${PROPS_TYPE(name, compiled.a11y.label)}

export function ${name}({
  size,
  speed = 1,
  loop,
  paused = false,
  className,
  label = ${JSON.stringify(compiled.a11y.label)},
}: ${name}Props) {
  const style = {
    "--sk-speed": speed,
    "--sk-play-state": paused ? "paused" : "running",
    ...(loop === undefined ? {} : { "--sk-iterations": loop ? "infinite" : 1 }),
  } as CSSProperties;

  return (
${renderRoot(compiled, root, ["style={style}"])}
  );
}
`;
}
